spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: springcldconfig-testdev
  security:
    user:
      name: admin
      password: enjoy
---
spring:
 profiles: default
 application:
      name: springcldconfig-testdefault
 security:
    user:
      name: zhangsan
      password: zhangsan133
    